// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using telecom.Modules.Telecom.Data;

#nullable disable

namespace telecom.Migrations
{
    [DbContext(typeof(TelecomContext))]
    [Migration("20260202145659_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("telecom")
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("telecom.Modules.Customer.Models.customer", b =>
                {
                    b.Property<Guid>("customer_uid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("created_by")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("created_date")
                        .HasColumnType("datetime2");

                    b.Property<string>("customer_first_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("customer_last_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("doc_addr_building")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("doc_addr_district")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("doc_addr_moo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("doc_addr_no")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("doc_addr_postcode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("doc_addr_province")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("doc_addr_soi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("doc_addr_sub_district")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("is_main_doc")
                        .HasColumnType("bit");

                    b.Property<string>("main_addr_building")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("main_addr_district")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("main_addr_moo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("main_addr_no")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("main_addr_postcode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("main_addr_province")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("main_addr_soi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("main_addr_sub_district")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("phone_number")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("register_package_uid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("updated_by")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("updated_date")
                        .HasColumnType("datetime2");

                    b.HasKey("customer_uid");

                    b.ToTable("customer", "telecom");
                });

            modelBuilder.Entity("telecom.Modules.Customer.Models.package", b =>
                {
                    b.Property<Guid>("package_uid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("created_by")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("created_date")
                        .HasColumnType("datetime2");

                    b.Property<int?>("internet_limit")
                        .HasColumnType("int");

                    b.Property<string>("package_name")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("phone_limit")
                        .HasColumnType("int");

                    b.Property<decimal?>("price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("updated_by")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("updated_date")
                        .HasColumnType("datetime2");

                    b.HasKey("package_uid");

                    b.ToTable("package", "telecom");
                });

            modelBuilder.Entity("telecom.Modules.Customer.Models.register_package", b =>
                {
                    b.Property<Guid>("register_package_uid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("created_by")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("created_date")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("customer_uid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("expired_date")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("package_uid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("register_date")
                        .HasColumnType("datetime2");

                    b.Property<string>("updated_by")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("updated_date")
                        .HasColumnType("datetime2");

                    b.HasKey("register_package_uid");

                    b.ToTable("register_package", "telecom");
                });
#pragma warning restore 612, 618
        }
    }
}
